// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ArInternalMetadata string
	CustomCommands     string
	Reviews            string
	SchemaMigrations   string
}{
	ArInternalMetadata: "ar_internal_metadata",
	CustomCommands:     "custom_commands",
	Reviews:            "reviews",
	SchemaMigrations:   "schema_migrations",
}
